version: 0.2

env:
  secrets-manager:
    - DOCKERHUB_USERNAME: DOCKERHUB_USERNAME
    - DOCKERHUB_PASSWORD: DOCKERHUB_PASSWORD
    - CDK_ECR_REPO: CDK_ECR_REPO
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - git clone https://github.com/aws/aws-cdk.git
      - cd aws-cdk
  pre_build:
    commands:
      - export GIT_COMMIT_ID=`git rev-parse HEAD`
      - export GIT_TAG=`git tag --points-at HEAD`
  build:
    commands:
      - yarn install
      - ./build.sh --skip-prereqs --skip-test
      - cd ..
      - codebuild-breakpoint
      - sh -c "$(wget https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"
      - echo "FROM jsii/superchain" >> Dockerfile_img
      - echo "WORKDIR home" >> Dockerfile_img
      - echo "COPY aws-cdk ." >> Dockerfile_img
      - echo "CMD [\"/bin/bash\"]" >> Dockerfile_img
      - docker build -t $CDK_ECR_REPO:$GIT_COMMIT_ID -t $CDK_ECR_REPO:latest -f Dockerfile_img . 
  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - docker push $CDK_ECR_REPO:$GIT_COMMIT_ID
      - docker push $CDK_ECR_REPO:latest
      - docker login --username $DOCKERHUB_USERNAME --password-stdin $DOCKERHUB_PASSWORD
      - docker tag $CDK_ECR_REPO:latest $DOCKERHUB_USERNAME/remote-cdk:latest
      - docker tag $CDK_ECR_REPO:latest $DOCKERHUB_USERNAME/remote-cdk:$GIT_COMMIT_ID
      - docker push $DOCKERHUB_USERNAME/remote-cdk:latest
      - docker push $DOCKERHUB_USERNAME/remote-cdk:$GIT_COMMIT_ID
